### ISSUE TITLE
question: where are the notes stored?

### ISSUE THREAD

**Issue by suredream** [betterRunner/context-note#17]
Any way to back-up and import/export the notes?

**Comment by NaturelLee** [comment]
It use [chrome.storage.local API](https://developer.chrome.com/docs/extensions/reference/storage/) like localStorage. 

> User data can be automatically synced with Chrome sync (using storage.sync).

I think It can be sync. Maybe in the future.

**Comment by betterRunner** [comment]
@suredream the exporting notes feature already existed (collapsed by the more button at the bottom of the extension) while the importing notes feature will be supported soon!

**Comment by betterRunner** [comment]
#22 adds the importing notes feature.

**Comment by suredream** [comment]
any risk I will lose the notes if I clean the chrome cache?

**Comment by betterRunner** [comment]
> any risk I will lose the notes if I clean the chrome cache?

The accepted answer of https://stackoverflow.com/questions/23210499/chrome-storage-local-persistence claims that "chrome.storage.local shouldn't be disappearing except on uninstallation". And I have also tried cleaning the chrome cache without losing the data.
