### ISSUE TITLE
footer collapse will hide the collapse button itself

### ISSUE THREAD

**Issue by KiritoXF** [betterRunner/context-note#20]
### How to reproduce
1. open the notebook, click the collapse button.
![image](https://user-images.githubusercontent.com/14950411/139409934-956ee565-f593-4384-92c2-dd1a7c550212.png)

2. the notebook will extend to fullscreen, but the collapse button will be out of the screen.
![image](https://user-images.githubusercontent.com/14950411/139410099-efa1a694-208e-433e-8dfb-ef548c28bf8b.png)

3. Shrink the screen to 80% and it will show again.
![image](https://user-images.githubusercontent.com/14950411/139410229-6477f402-1707-46cc-9e98-086c38582891.png)

**Comment by betterRunner** [comment]
Hi @KiritoXF, could you share your screen resolution?

**Comment by betterRunner** [comment]
@KiritoXF use dynamic width according to the browser width to fix it.
