### ISSUE TITLE
There is a bug with "handleClickOutsideEditor"

### ISSUE THREAD

**Issue by sockball** [betterRunner/context-note#27]
Now, when I have a note in notebook, it will trigger "handleClickOutsideEditor" wherever I click if I didn't focus the editor. And "delete" operation doesn't work.

I try this and it would be fixed.

```
// src/content-scripts/renderer/popup/note-book/note.vue #201

const handleClickOutsideEditor = () => {
  // add 3 lines
  if (!enableEditor.value) {
    return;
  }

  enableEditor.value = false;

  // save the note
  if (!notSelected.value) {
...
```

**Comment by betterRunner** [comment]
@sockball Yes you are right and your code is the way to fix it. Thanks a lot!
Would you like to make a pull request?
