### ISSUE TITLE
feature suggestions: generate link of selected text

### ISSUE THREAD

**Issue by chenboshuo** [betterRunner/context-note#34]
I think [Link to Text Fragment](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg/related) is also a good extension, and I hope this extensions can generate url for selected text, it would it is more elegent of the output format

**Comment by betterRunner** [comment]
Hi chenboshuo, I guess this feature is already existed if i'm not mistaken? When you open the note by clicking the link, it will jump back to the location of the note and the url is with the noteId.
![image](https://user-images.githubusercontent.com/7123136/141646500-5e74e54d-494d-493f-8f0c-8f12aad5084a.png)
Please correct me if I am wrong.

**Comment by chenboshuo** [comment]
Well, This link can be located when you click it, but can't locate text when you copy it, if I want to share this link, it is better if it can locate the selected text. Thanks for your attention.

**Comment by betterRunner** [comment]
Thanks, I tried [Link to Text Fragment](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg/related) and I think I understand what your need is.

The copied url of the example of Link to Text Fragment is `https://web.dev/#:~:text=Let's%20build%20the-,future,-of%20the%20web` which uses the postfix `:~:text=xxx` to highlight the selected text, if you scroll the page then the postfix would disappear. I think this feature is pretty good when you want to share this selected text with other people. But as context note is a note-taking extension, it might focus more on how to store the selected text into storage and show it again next time you open, which can not be achieved by the above method.

So as for the need to share the link, I would suggest using [Link to Text Fragment] instead.

**Comment by chenboshuo** [comment]
Thanks, I got it, this is a good product positioning, and I think the extension will be more prefect.
