### ISSUE TITLE
I would like to support the editing of the corresponding web site URL

### ISSUE THREAD

**Issue by banduoba** [betterRunner/context-note#38]
Some web pages do not get the full URL, which leads to opening the same web page as other related pages can not be marked in the page.

**Comment by betterRunner** [comment]
Thanks for the feedback. Could you provide some samples with this bug？

**Comment by banduoba** [comment]
For example, this URL:https://detail.tmall.com/item.htm?id=658300767664,
Open each page only the number after id= is different, but now open each page is the same

![image](https://user-images.githubusercontent.com/4811366/147405356-5f87426a-a076-4584-a5b1-8376db8623aa.png)

**Comment by betterRunner** [comment]
fixed by #41
