### ISSUE TITLE
Feature request: Support LTI protocol

### ISSUE THREAD

**Issue by fishfree** [betterRunner/context-note#39]
It will be very useful for online learning to support the [LTI ](https://www.imsglobal.org/activity/learning-tools-interoperability)protocol!

**Comment by betterRunner** [comment]
Hi @fishfree , I have checked [LTI ](https://www.imsglobal.org/spec/lti/v1p3/) and also found a [lti-js](https://github.com/Cvmcosta/ltijs) package. As far as I know supporting this protocol needs a server right? This extension just stores the data in your local `chrome.storage`, which I guess is not suitable to match this feature? Correct me if I am wrong or please provide more details about how to support it, thanks!

**Comment by fishfree** [comment]
@betterRunner Yes, it requires a server to persist the notes. We should thank you very much!
