### ISSUE TITLE
Feature Request: Shortcut keys

### ISSUE THREAD

**Issue by pelly** [betterRunner/context-note#42]
It would be really handy to have shortcut keys for at least closing the context note UI. Currently after I create a note I have to scroll to the top of the UI to close the context note overlay which is obscuring the webpage underneath. As I generate more notes it becomes more and more cumbersome.

Overall I really like the concept!

**Comment by betterRunner** [comment]
The close button is fixed now instead of flowing with scroll so I guess the shortcut would also be unnecessary, thanks for the nice feedback.
